apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
  labels:
    app: zomato
spec:
  replicas: 4
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: mydockerprojectfor5pm
        image: sueesh144/netflixrepo:myzomatoimage
        ports:
        - containerPort: 3000

  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: zomato-svc
  spec:
    type: LoadBalancer
    selector:
      app: zomato
    ports:
    - protocol: TCP
      port: 3000          
      targetPort: 3000  


