apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
  labels:
    app: zomato
spec:
  replicas: 5
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: mydockerprojectfor5pm
        image: tanmay18121/gabrimage:latest
        ports:
        - containerPort: 80
